# pragma: allowlist secret
global:
  domain: minikube.test

configs:
  secret:  # pragma: allowlist secret
    argocdServerAdminPassword: "<bcrypt-hash-here>"  # pragma: allowlist secret
  dex.config: |  # pragma: allowlist secret
    connectors:
    - type: github
      id: github
      name: GitHub
      config:
        clientID:
        clientSecret:
        orgs:
        - name: QCDIS
  ingress:
    enabled: true
    className: "nginx"
    hosts:
      - minikube.test
    paths:
        - /argo-cd
